spring:
  application:
    name: Boatsvc
  datasource:
    url: jdbc:h2:mem:db_boat
    hikari:
      driver-class-name: org.h2.Driver
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 3
jwt:
  secret-key: 'test'
  token-expiration-after-days: 1
  token-refresh-expiration-after-days: 30
  token-prefix: 'Bearer '

logging.level:
  ch.challenge: debug

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    #    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${db.path}/db_boat
  sql:
    init:
      mode: always
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  jpa:
#    database: H2
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#  sql:
#    init:
#      platform: org.h2.Driver
server:
  port: 8082
