spring:
  application:
    name: Boatsvc
  datasource:
    url: jdbc:h2:mem:db_boat
logging.level:
  ch.challenge: debug
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    #    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${db.path}/db_boat
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  jpa:
#    database: H2
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#  sql:
#    init:
#      platform: org.h2.Driver
